{{- define "shared.ingress" -}}
{{- $fullName := include "shared.fullname" . -}}
{{- range $path := .Values.ingress.paths }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}{{ regexReplaceAll "[^a-zA-Z0-9]+" .path "-" | trimAll "-" }}
  labels:
    {{- include "shared.labels" $ | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    {{- with $.Values.ingress.className }}
    acme.cert-manager.io/http01-ingress-class: {{ . }}
    {{- end }}
    {{- with $.Values.middleware }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-{{ $fullName }}-cors@kubernetescrd
    {{- end }}
    {{- with $.Values.ingress.annotations }}
      {{- toYaml . | nindent 4}}
    {{- end }}
    {{- with .annotations }}
      {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  {{- with $.Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  {{- $hostnames := default (list $.Values.ingress.hostname) $.Values.ingress.hostnames -}}
  {{- range $hostname := $hostnames }}
  - host: {{ $hostname }}
    http:
      paths:
      - path: {{ $path.path }}
        pathType: {{ $path.pathType }}
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $.Values.service.port }}
  {{- end }}
  tls:
  {{- range $hostname := $hostnames }}
  - hosts:
    - {{ $hostname }}
    secretName: {{ $fullName }}-{{ regexReplaceAll "[^a-zA-Z0-9]+" $hostname "-" | trimAll "-" }}-cert
  {{- end }}
---
{{- end }}
{{- end -}}
