kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: XXX
  name: deny-traffic-to-XXX-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          client: "XXX-app"
