{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            {{- toYaml .Values.cronjob.securityContext | nindent 12 }}
          restartPolicy: OnFailure
          containers:
            - name: {{ .Values.cronjob.name }}
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
              command: {{ toJson .Values.cronjob.command }}
              args: {{ toJson .Values.cronjob.args }}
              resources:
                {{- toYaml .Values.cronjob.resources | nindent 16 }}
{{- end }}
