{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      securityContext:
        {{- toYaml .Values.job.securityContext | nindent 8 }}
      containers:
        - name: {{ .Values.job.name }}
          image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
          imagePullPolicy: {{ .Values.job.image.pullPolicy }}
          command: {{ toJson .Values.job.command }}
          args: {{ toJson .Values.job.args }}
          resources:
            {{- toYaml .Values.job.resources | nindent 12 }}
{{- end }}
