{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  podSelector:
    {{- toYaml .Values.networkPolicy.podSelector | nindent 4 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}

  ingress:
    - from:
        {{- range .Values.networkPolicy.ingress.fromNamespaces }}
        - namespaceSelector:
            matchLabels:
              name: {{ . }}
        {{- end }}
        {{- range .Values.networkPolicy.ingress.fromCIDRs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}

  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    - to:
        {{- range .Values.networkPolicy.egress.toCIDRs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
  {{- end }}
{{- end }}
