apiVersion: v1
kind: Service
metadata:
  name: alert-manager-service
  namespace: monitoring
spec:
  ports:
  - port: 9093
    targetPort: 9093
  selector:
    app: alert-manager
  type: LoadBalancer
