apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}-service
  namespace: {{ .Values.common.namespace }}
spec:
  ports:
  - port: {{ .Values.common.ports.containerPort }}
    targetPort: {{ .Values.common.ports.containerPort }}
  selector:
    app: {{ .Values.common.name }}
  type: {{ .Values.service.type }}
