{{- define "common.cronjob" -}}
{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "common.fullname" . }}-cronjob
  namespace: {{ include "common.namespaceName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            {{- toYaml .Values.cronjob.securityContext | nindent 12 }}
          restartPolicy: {{ .Values.cronjob.restartPolicy | default "OnFailure" }}
          containers:
            - name: {{ include "common.name" . }}-cronjob
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
              command: {{ toJson .Values.cronjob.command }}
              args: {{ toJson .Values.cronjob.args }}
              resources:
                {{- toYaml .Values.cronjob.resources | nindent 16 }}
{{- end }}
{{- end -}}