repositories:
  - name: metallb
    url: https://metallb.github.io/metallb

releases:
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    # https://artifacthub.io/packages/helm/metallb/metallb
    version: 0.13.10
    createNamespace: true
    hooks:
      - events: ["apply"]
        showlogs: true
        command: kubectl
        args: ["apply", "-f", "ip-pool.yaml"]
