controller:
  resources:
    limits:
      cpu: 100m
      memory: 90Mi
    requests:
      cpu: 100m
      memory: 90Mi

  livenessProbe:
    httpGet:
      path: "/healthz"
      port: 10254
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    httpGet:
      path: "/healthz"
      port: 10254
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

  kind: DaemonSet
  hostNetwork: true
  daemonset:
    useHostPort: true
  publishService:
    enabled: true

  ingressClass: nginx
  ingressClassResource:
    name: nginx
    enabled: true
    default: false

  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
