apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: psuja-local-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: psuja.tld
  secretName: psuja-tld
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: psuja-self-signed-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: psuja-self-signed-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: psuja-cluster-issuer
spec:
  ca:
    secretName: psuja-tld