repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  chart: jetstack/cert-manager
  namespace: cert-manager
  createNamespace: true
  # https://artifacthub.io/packages/helm/cert-manager/cert-manager
  version: v1.16.2
  set:
  - name: installCRDs
    value: true
  - name: ingressShim.defaultIssuerName
    value: letsencrypt
  - name: ingressShim.defaultIssuerKind
    value: ClusterIssuer
  - name: ingressShim.defaultIssuerGroup
    value: cert-manager.io
  values:
  - cert-manager.yaml
