repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
#   # https://artifacthub.io/packages/helm/cert-manager/cert-manager
    version: v1.17.2
    createNamespace: true
    values:
      - values.yaml
    hooks:
      - events: ["apply"]
        showlogs: true
        command: kubectl
        args: ["apply", "-f", "issuer.yaml"]
    #   - events: ["apply"]
    #     showlogs: true
    #     command: kubectl
    #     args: ["apply", "-f", "ca.cluster.yaml"]
    # hooks:
      - events: ["prepare"]
        command: kubectl
        args:
          - apply
          - -f
          - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.crds.yaml
